services:
  - name: fastapi-backend
    type: web
    env: docker
    plan: free
    dockerfilePath: Dockerfile.backend

  - name: streamlit-frontend
    type: web
    env: docker
    plan: free
    dockerfilePath: Dockerfile.frontend
